version: "3"

services:
  # tracker1 容器
  fastdfs-tracker1:
    image: registry.cn-hangzhou.aliyuncs.com/zhengqing/fastdfs:latest
    container_name: fastdfs_tracker1
    hostname: fastdfs-tracker1
    networks:
      - fastdfs-network
    command: tracker
    volumes:
      - ./fastdfs/tracker1_data:/var/fdfs
    ports:
      - "22122:22122"

  # tracker2 容器
  fastdfs-tracker2:
    image: registry.cn-hangzhou.aliyuncs.com/zhengqing/fastdfs:latest
    container_name: fastdfs_tracker2
    hostname: fastdfs-tracker2
    networks:
      - fastdfs-network
    command: tracker
    volumes:
      - ./fastdfs/tracker2_data:/var/fdfs
    ports:
      - "22123:22122"

  # storage1 容器
  fastdfs-storage1:
    image: registry.cn-hangzhou.aliyuncs.com/zhengqing/fastdfs:latest
    container_name: fastdfs_storage1
    hostname: fastdfs-storage1
    networks:
      - fastdfs-network
    environment:
      - TRACKER_SERVER=fastdfs-tracker1:22122,fastdfs-tracker2:22122
      - GROUP_NAME=group1
    command: storage
    depends_on:
      - fastdfs-tracker1
      - fastdfs-tracker2
    volumes:
      - ./fastdfs/storage1_data:/var/fdfs
    ports:
      - "8888:8888"
      - "23000:23000"

  # storage2 容器
  fastdfs-storage2:
    image: registry.cn-hangzhou.aliyuncs.com/zhengqing/fastdfs:latest
    container_name: fastdfs_storage2
    hostname: fastdfs-storage2
    networks:
      - fastdfs-network
    environment:
      - TRACKER_SERVER=fastdfs-tracker1:22122,fastdfs-tracker2:22122
      - GROUP_NAME=group1
    command: storage
    depends_on:
      - fastdfs-tracker1
      - fastdfs-tracker2
    volumes:
      - ./fastdfs/storage2_data:/var/fdfs
    ports:
      - "8889:8888"
      - "23001:23000"

networks:
  fastdfs-network:
    driver: bridge
